name: Generate Pacman Contribution Graph

# Executa apenas manualmente para economizar minutos
on: workflow_dispatch

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Limita o tempo de execução
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Baixa apenas o necessário para economizar tempo
          fetch-depth: 1
          sparse-checkout: |
            output/
            .gitignore

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Versão específica é mais rápida
          cache: 'pip'  # Habilita cache de dependências

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir matplotlib requests

      - name: Generate Pacman Graph
        run: |
          mkdir -p output
          # Baixa o script apenas se necessário
          if [ ! -f pacman.py ]; then
            curl -s https://raw.githubusercontent.com/yoshi389111/github-pancman-contribution/main/pacman.py -o pacman.py
          fi
          
          # Gera os gráficos apenas se houver alterações
          python pacman.py Matheuskocotem --dark > output/pacman-contribution-graph-dark.svg
          python pacman.py Matheuskocotem > output/pacman-contribution-graph.svg

      - name: Commit changes
        if: success()
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add output/
          # Usa --allow-empty para garantir que o commit seja criado mesmo sem alterações
          git commit --allow-empty -m "update pacman contribution graph"
          git push
